---
title: "User Guide and FAQs"
output:
  html_document:
    toc: true
    toc_float: true
---
<style>
body {
text-align: justify}
</style>

\

# User Interface

\

## Leveraging the effective R trend plots to greater effect.
The plots show all the data that each one is capable of showing upon loading. To override this follow the below steps:

- Double-click on any item in the legend - This clears off the clutter in the plot area. 
- Select all the regions that you with to compare by single clicking on the region names in the legend.
- Single clicking toggles between select and unselect - please use this as you wish.
- The right top corner of each plot has a control panel that allows you to toggle the mouse-hover characteristics. 
- Choosing the single-arrow icon (third from right) would cause the date and R value for a specific region to be shown on mouse hover. 
- While the two-arrow icon (second from right) would let you see the dates and R values for all the selected regions for a given date simultaneously. 
- Selecting a region on the plot using mouse click-and-drag allows to zoom into areas on interest.
- All district-level plots have Effective R trends for India and the corresponding state to allow for easy comparison.
- Each plot contains a large amount of data. The above selection flow is recommended help you use the information in the plots to greater effect. 

\

## Utilising tables in weekly effective R reports
Some of tables shown in the weekly effective R reports are interactive with their own search bar and column-wise sorting options. The user is recommended to use these features as they deem fit to seek out data relevant for them.

\

## What is the difference between weekly and daily effective R analysis?
The weekly R reports provides the reader with weekly snapshots of the situation. It assess the effective R for the regions for previous week (Sunday through Saturday) as compared to the the preceding week. Such comparison is presented here with the hope that the decision-maker would be able to assess the progress of the situation using fixed time intervals. Expectation is that the estimates thus generated are more robust as it uses a stochastic smoothing method.

Daily R plots provide the users with a near-runtime situation analysis while also showing how a region has progressed in the past. These estimates use a 7-day simple moving average smoothing. It provides the user with a daily-updated, most recent estimates of effective R for each region.

\

## Will there be further updates?
This website will be updated a minimum of once daily. Aim is to make the updated visualisations available before 9 AM (UTC +5:30) to the users. Automation of updates is being worked upon to ensure consistent and reliable updates into the future.

\

\

# Reproduction Number

\

## What is effective reproductive number?
Effective reproductive number (Rt) is the average number of secondary infections per infectious case in the population at any given point in time.

\

## How do I interpret effective reproductive number?
- Effective R (Rt) is a number between 0 to positive infinity (well, theoretically).
- If the Rt = 1, each case would transmit the disease to one other person. Hence, the number of new cases will remain constant. The cumulative incidence would show a linear increase.
- If Rt > 1, each case will transmit the disease to more than one other person (equal to Rt value). The daily number of reported new cases will increase, and cumulative incidence increases exponentially.
- If Rt < 1, each case would transmit to less than one other person (again, equal to the Rt value), this would mean that the daily number of reported new cases would come down, eventually the infection would get contained.
- A simplified analogy to understand this is to see the daily growth rate in cases as velocity/speed. The effective Rt is like acceleration.

\

## Would lockdowns show an immediate change in effective reproductive numbers?
Ideally a lag is to be expected from the commencement of lockdown till perceivable change in effective R is seen due to the following reasons:

- The serial interval - the time between an infector becomes symptomatic till the infected (person who got infected by the infector) became symptomatic. Current estimates are about 5 days. [If you are really curious, you may also read up about generation interval which is quite difficult to estimate accurately in real-world setting].
- Testing and reporting lags - as the number of samples collected each day increases, the testing system gets stressed leading to delays in testing and reporting. This may or may not be significant in your context. This can be a significant contributor to the lag of indicators.
- Community vs Household transmission - Getting infected from the outside community can be controlled by lockdown, however, getting infected inside ones' own home via a person who got infected in the community will happen even with lockdown in place. There will be a drop in this eventually as lockdown causes less people to get infected in the community and take the pathogen to their homes. Household transmission may lead to a share of positive cases despite the lockdown being in place - but then again, lockdowns are less effective, and not designed to reduce household transmissions.

\

## Can the R values be used know the risk of getting COVID-19?
In a way, yes. But it may not be that intuitive for daily use. An effective R above 1 does point to higher risk. A better indicator for household level decision making are the test positivity rates. 

Regardless of what the numbers show, it is highly recommended that you take all necessary precautions like double masking, proper hand hygiene, physical distancing, and practice full compliance to lockdowns and/or other locally relevant containment strategies at all times.

\


\

# Legal

\

## MIT 
Copyright 2021 Dr. Shaik Nishan AShraf

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

\

## Creative Commons
This work is licensed under the Creative Commons Attribution 4.0 International License. To view a copy of this license, visit
http://creativecommons.org/licenses/by/4.0/.