---
title: "Lakshadweep"
---
<style>
body {
text-align: justify}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages, include = FALSE, echo = FALSE}
library(tidyverse)
library(plotly)
```

```{r Data, include = FALSE}
india <- read_csv("India.csv")
states <- read_csv("States.csv")
districts <- read_csv("Districts.csv")

state_name <- "Lakshadweep"

# Prepping =======================
india <- india %>% 
  mutate(Region = "India") %>% 
  rename(Rt = smR) %>% 
  dplyr::select(Region, Date, Rt)

states <- states %>% 
  filter(Region != "Placeholder") %>% 
  filter(Date >= as.Date("2020-05-15")) %>% 
  filter(Region == state_name)

districts <- districts %>% 
  filter(State != "Placeholder") %>% 
  filter(Date >= as.Date("2020-05-15")) %>%
  filter(State == state_name) %>% 
  dplyr::select(District, Date, smR) %>% 
  rename(Region = District,
         Rt = smR)


# Merging ==============================
data <- bind_rows(india, states)
data <- bind_rows(data, districts)

# Sanity checks =======================
data <- data %>% 
  filter(Rt <= 5)

rm(india, states, districts)
```



\

Trends in effective R numbers smoothed using 7-day simple moving average for `r state_name`.


```{r Trend A_N R, echo = FALSE, fig.height = 10, fig.width = 10}

#33e2e8

p <- data %>% 
  ggplot(aes(x = Date, y = Rt)) +
  geom_line(aes(colour = Region)) +
  geom_hline(aes(yintercept = 1), colour = "#acb5b5", linetype = "dashed") +
  labs(x = "",
       y = "Effective R (smoothed)",
       title = paste0("Trends in effective R numbers for ",  state_name)) +
  theme_minimal() +
    theme(legend.position = "bottom")

ggplotly(p, dynamicTicks = TRUE) %>% 
  layout(legend = list(x = 0, y = -300, orientation = 'h'))
```

\

*(Note: The plot is interactive!)*