---
title: <strong>Mastering R</strong>
subtitle: <center><i>60-Day Roadmap to R Expertise</i></center>
author: <i>Go from beginner to advanced</i>
fontfamily: Helvetica
output:
  html_document:
    theme: flatly
---
<style type="text/css">


body {
  font-family: Helvetica;
}

h1,h2,h3,h4,h5,h6{
  font-family: Helvetica;
}

h1.title {
  text-align: center;
  font-size: 60px;
  padding-top: 2%;
  
}

h4.subtitle {
  text-align: center;
  font-size: 20px;
  padding-top: 1%;
}


h4.author {
  text-align: center;
  padding-top: 1%;
  font-size: 18px;
  
}

h4.date {
  text-align: center;
  padding-top: 0.75%;
  padding-bottom: 0.5%;
  font-size: 20px;
  
}

.button {
border-width: 1px;
border-style: solid;
border-radius: 12px;
border-color: white;
background-color: #2d64bc;
padding: 2px 2px;
text-align: center;
display: inline-block;
font-size: 18px;
width: 25%;
height: 60px;
transition-duration: 0.1s;
color: white;
}

.button:hover {
  background-color: #36AE7C; /* Green */
  border-color: #36AE7C;
  color: black;
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
}

.button_2 {
border-width: 1px;
border-style: solid;
border-radius: 12px;
border-color: white;
background-color: #2d64bc;
padding: 2px 2px;
text-align: center;
display: inline-block;
font-size: 20px;
width: 100%;
height: auto;
transition-duration: 0.1s;
color: white;
}

.button_2:hover {
  background-color: #36AE7C; /* Green */
  border-color: #36AE7C;
  color: black;
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
}

.button_3 {
border-width: 1px;
border-style: solid;
border-radius: 12px;
border-color: white;
background-color: #2d64bc;
padding: 2px 2px;
text-align: center;
display: inline-block;
font-size: 20px;
width: 100%;
height: auto;
transition-duration: 0.1s;
color: white;
}

.button_3:hover {
  background-color: #36AE7C; /* Green */
  border-color: #36AE7C;
  color: black;
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
}

</style>

\

<center><button class="button button" autofocus onclick="window.location.href ='https://rzp.io/l/mastering-r-expert'"><strong>Begin mastery</strong></button></center>

\

\

::: {style="background-color: white; font-size: 18px"}

<center>
<h3>
<strong>
About the course
</strong>
</h3>
</center>

<center>

Mastering R is a beginner-friendly R Programming course focused on medical, public health and social science professionals where I take you through the basics, data cleaning and management, and data visualization and reporting of data. A unique 60-day learning pathway delivered to you daily in small, bite-sized lessons not exceeding 30 minutes a day.

</center>
:::

\

::: {style="background-color: #f7f5e6; line-height: 1.8; text-align: center;"}
\

<center>

<h3>

<strong>Would you answer a 'Yes' any of the following?</strong>

</h3>

</center>

\

**You are a beginner to data, programming or  analytics**\
**You are a busy working professional or student for whom time is always at a premium?**\
**Do you want to become a data analytics expert?**\
**Are you planning on performing your analysis in R?**\
**Do you wish to explore analytics for public health/medical research?**\
**Do you wish to handle data more efficiently?**\
**Do you wish to automate your analysis and reporting?**\
**Do you wish to master the art of data visualization to shine in your career?**\

\
:::

\

::: {style="background-color: white; line-height: 1.8; text-align: center; font-size: 20px"}
**If you answered ‘Yes’ to any of the above questions, this course will be perfect for you.**
:::

\

::: {style="background-color: #f7f5e6; line-height: 1.8; text-align: center;"}
\

<center>

<h3>

<strong>What is so special about this course?</strong>

</h3>

</center>

\
**R course focused at medical research, public health, and social science research applications**\
**Simulated, and actual real-world datasets to practice on and for assignments**\
**I share my actual research/data science workflows used for real-world projects**\
**A Discord community which is a direct line to me**\
\
:::

:::: {style="font-size: 20px; text-align: center;"}

**You won't get this level of focus elsewhere!** \
::::

\

<center><button class="button button" onclick="window.location.href ='https://rzp.io/l/mastering-r-expert'"><strong>Start learning</strong></button></center>

\


::: {style="background-color: #f7f5e6; line-height: 1.8; text-align: center;"}
\

<center>

<h3>

<strong>What skills do you stand to gain from this course?</strong>

</h3>

</center>

\
**You gain a thorough understanding of data, data analytics and R.**\
**You can independently take on data management, cleaning and analysis tasks at work.**\
**You gain knowledge of data analytics best practices.**\
**You gain skills and knowledge behind beautiful data visualizations.**\
**You learn how to automate your periodic reports by leveraging the power of R.**\
**You get to show these skills at your work and accelerate your career growth.**\
**This course will be your stepping stone to data science.**\
\
:::

:::: {style="font-size: 20px; text-align: center;"}

**Best part is the course is structure in such a way that you can learn about 30 minutes a day.** \
::::

\

<center><button class="button button" onclick="window.location.href ='https://rzp.io/l/mastering-r-expert'"><strong>Enroll to begin learning</strong></button></center>

\

\

:::::: {style="display: flex"}

:::::{style="background-color: white; line-height: 1.8; text-align: left; width: 31%; padding-left: 2%; padding-right: 2%; border-width: 1px; border-style: solid; border-radius: 12px; border-color: #e9e9e9; font-size: 16px;"}

<h3>BASIC</h3>
20-DAY COURSE\
(Least recommended)\
\
&#10003; Fundamentals of R and data \
&#10003; Daily drip feed of lessons, quizzes and assignments \
&#10003; Email reminders \
&#10003; Access to Basic channels of Mastering R community \
&#10003; Certificate upon successful completion \
&#10003; Access to lessons for 90 days from date of enrollment \
\
\
<left><button class="button button_2" onclick="window.location.href ='https://rzp.io/l/mastering-r-basic'">&#8377; 1477</button></left>


:::::

::::: {style="background-color: white; line-height: 1.8; text-align: center; width: 1%;"}
:::::

:::::{style="background-color: white; line-height: 1.8; text-align: left; width: 31%; padding-left: 2%; padding-right: 2%; border-width: 1px; border-style: solid; border-radius: 12px; border-color: #e9e9e9; font-size: 16px;"}

<h3>INTERMEDIATE</h3>
37-DAY COURSE\
(Least popular)\
\
&#10003; Everything in Basic plan \
&#10003; Data management with Tidyverse \
&#10003; Access to Basic & Intermediate channels of Mastering R community \
\
\
\
\
<left><button class="button button_2" onclick="window.location.href ='https://rzp.io/l/mastering-r-intermediate'">&#8377; 2877</button></left>\

:::::

::::: {style="background-color: white; line-height: 1.8; text-align: center; width: 1%;"}
:::::

:::::{style="background-color: #DAEAF1; line-height: 1.8; text-align: left; width: 35%; padding-left: 2%; padding-right: 2%; border-width: 1px; border-style: solid; border-radius: 12px; border-color: #eeeeee; box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19); font-size: 16px;"}

<h3><strong>EXPERT</strong></h3>
**60-DAY COURSE**\
**(Most Popular & Recommended)**\
\
&#10003; Everything in Intermediate \
&#10003; Data visualization theory and hand-on with ggplot2 package \
&#10003; Repeatable, reproducible, and automated reporting of analysis with RMarkdown \
&#10003; Access to Basic, Intermediate & Expert channels of Mastering R community \
&#10003; Discounted pricing on all live workshops during the course duration\
\
<left><button class="button button_3" onclick="window.location.href ='https://rzp.io/l/mastering-r-expert'">&#8377; 3377</button></left>\

:::::

::::::
